apiVersion: v1
kind: Pod
metadata:
  name: build-pod
  annotations:
    container.apparmor.security.beta.kubernetes.io/buildah: unconfined
spec:
  imagePullSecrets:
    - name: regcred
  restartPolicy: Never
  hostAliases:
    - hostnames:
      - "jenkins.rafael.co.il"
      ip: "10.27.208.49"
    - hostnames:
      - "artifactory.rafael.co.il"
      ip: "10.27.208.11"
  containers:
    - name: "docker"	
      image: docker:dind	
  	  command:
        - "dockerd-entrypoint.sh"
      tty: true
      securityContext:
        allowPrivilegeEscalation: false
      resources:
        requests:
          cpu: 500m
          memory: 1Gi
        limits:
          cpu: 1
          memory: 2Gi    


    - name: "python"
      image: "artifactory.rafael.co.il:6039/utils/python:3.9"
      pullPolicy: IfNotPresent
      command:
        - "cat"
      tty: true
      securityContext:
        allowPrivilegeEscalation: false
    - name: python-node
      image: artifactory.rafael.co.il:6039/utils/python-node:19.6.1
      pullPolicy: IfNotPresent
      command:
        - cat
      tty: true
      securityContext:
        allowPrivilegeEscalation: false
      
    - name: node
      image: docker.io/node:16.14.2-slim
      pullPolicy: IfNotPresent
      command:
        - cat
      tty: true
      securityContext:
        allowPrivilegeEscalation: false
      
    # - name: node-junit
    #   image: node:0.10.34
    #   pullPolicy: IfNotPresent
    #   command:
    #     - cat
    #   tty: true
    #   securityContext:
    #     allowPrivilegeEscalation: false
        
    - name: trivy
      image: artifactory.rafael.co.il:6039/utils/trivy:0.45.0.internal-1
      command:
        - cat
      tty: true
      securityContext:
        allowPrivilegeEscalation: false
        
    - name: trivy-new
      image: artifactory.rafael.co.il:6039/utils/trivy:latest
      command:
        - cat
      tty: true
      securityContext:
        allowPrivilegeEscalation: false
        
    - name: cosign
      image: bitnami/cosign:latest
      command:
        - cat
      tty: true
      securityContext:
        allowPrivilegeEscalation: false   
        
    - name: buildah
      image: artifactory.rafael.co.il:6039/utils/buildahstableaws:v1.23.1-1
      #image: quay.io/buildah/stable:v1.23.1
      pullPolicy: IfNotPresent
      command:
      - cat
      tty: true
      securityContext:
        # allowPrivilegeEscalation: false
        runAsNonRoot: true
        runAsUser: 1000
      volumeMounts:
        - name: varlibcontainers
          mountPath: /var/lib/containers
          
    - name: kics
      image: artifactory.rafael.co.il:6039/utils/checkmarx/kics
      pullPolicy: IfNotPresent
      command:
        - "cat"
      tty: true
      resources:
        requests:
        ephemeral-storage: "1Gi"
        limits:
        ephemeral-storage: "2Gi"
      securityContext:
        allowPrivilegeEscalation: false
        
    - name: curl
      image: artifactory.rafael.co.il:6039/utils/alpine/curl:latest
      pullPolicy: IfNotPresent
      command:
        - "cat"
      tty: true
      securityContext:
        allowPrivilegeEscalation: false
      
    - name: kubectl
      image: bitnami/kubectl
      pullPolicy: IfNotPresent
      command: ["sleep"] 
      args: ["infinity"]
      volumeMounts:
        - name: kubeconfig
          mountPath: /root/.kube
      securityContext:
        allowPrivilegeEscalation: false
        
    - name: jnlp
      image: artifactory.rafael.co.il:6003/jenkins/inbound-agent:alpine3.19-jdk21
      
  volumes:
    - name: varlibcontainers
    - name: kubeconfig
      secret:
        secretName: kubeconfig-secret
        items:
          - key: config
            path: config


