apiVersion: v1
kind: Pod
metadata:
  name: jnlp-pod
spec:
  containers:
    - name: jnlp
      image: artifactory.rafael.co.il:6003/jenkins/inbound-agent:alpine3.19-jdk21
      command: ["tail", "-f", "/dev/null"]  # Keeps the container running indefinitely
  restartPolicy: Always
  hostAliases:
    - hostnames:
      - "jenkins.rafael.co.il"
      ip: "10.27.208.49"
    - hostnames:
      - "artifactory.rafael.co.il"
      ip: "10.27.208.11"
